---
  # Virtual vEOS Lab Devices
  SW01:
    hostname: 192.168.179.41
    username: "admin"
    password: "Arista!1234"
  SW02:
    hostname: 192.168.179.42
    username: "admin"
    password: "Arista!1234"
  
